name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: sudo apt install libdatetime-perl -y
    - name: Do tests
      run: bash ./test.sh
